<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">utilStringToAny</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required string</value>
    <value>[i] field:0:required type {"BigDecimal","BigInteger","Boolean","Character","Date","Double","Integer","Float","Long","MBoolean","MDouble","MFloat","MInteger","MLong","MShort","Object","Short"}</value>
    <value>[i] field:0:optional dateFormat {"dd.MM.yyyy"}</value>
    <value>[o] object:0:required AnyType</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIGN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0K
SURhdGEgaW5wdXQgPSBJRGF0YVV0aWwuZ2V0SURhdGEoY3Vyc29yLCAiaW5wdXREb2N1bWVudCIp
Ow0KU3RyaW5nIHN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAic3RyaW5nIik7
DQpTdHJpbmcgdHlwZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAidHlwZSIpOw0KU3Ry
aW5nIGRhdGVGb3JtYXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwgImRhdGVGb3JtYXQi
KTsNCmN1cnNvci5kZXN0cm95KCk7DQovLyBwaXBlbGluZQkNCg0KaWYgKHN0cmluZyA9PSBudWxs
IHx8IHN0cmluZy5sZW5ndGgoKSA9PSAwKQ0Kew0KICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIkFu
eVR5cGUiLCBudWxsKTsNCn0NCmVsc2UgaWYgKHR5cGUuZXF1YWxzKCJTdHJpbmciKSkNCnsNCiAg
SURhdGFVdGlsLnB1dChjdXJzb3IsICJBbnlUeXBlIiwgc3RyaW5nKTsNCn0NCmVsc2UgaWYgKHR5
cGUuZXF1YWxzKCJJbnRlZ2VyIikpDQp7DQogIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiQW55VHlw
ZSIsIG5ldyBJbnRlZ2VyKHN0cmluZykpOw0KfQ0KZWxzZSBpZiAodHlwZS5lcXVhbHMoIk1JbnRl
Z2VyIikpDQp7DQogIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAiQW55VHlwZSIsIG5ldyBNSW50ZWdl
cihzdHJpbmcpKTsNCn0NCmVsc2UgaWYgKHR5cGUuZXF1YWxzKCJTaG9ydCIpKQ0Kew0KICBJRGF0
YVV0aWwucHV0KGN1cnNvciwgIkFueVR5cGUiLCBuZXcgU2hvcnQoc3RyaW5nKSk7DQp9DQplbHNl
IGlmICh0eXBlLmVxdWFscygiTVNob3J0IikpDQp7DQogIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAi
QW55VHlwZSIsIG5ldyBNU2hvcnQoc3RyaW5nKSk7DQp9DQplbHNlIGlmICh0eXBlLmVxdWFscygi
TG9uZyIpKQ0Kew0KICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIkFueVR5cGUiLCBuZXcgTG9uZyhz
dHJpbmcpKTsNCn0NCmVsc2UgaWYgKHR5cGUuZXF1YWxzKCJNTG9uZyIpKQ0Kew0KICBJRGF0YVV0
aWwucHV0KGN1cnNvciwgIkFueVR5cGUiLCBuZXcgTUxvbmcoc3RyaW5nKSk7DQp9DQplbHNlIGlm
ICh0eXBlLmVxdWFscygiRmxvYXQiKSkNCnsNCiAgSURhdGFVdGlsLnB1dChjdXJzb3IsICJBbnlU
eXBlIiwgbmV3IEZsb2F0KHN0cmluZykpOw0KfQ0KZWxzZSBpZiAodHlwZS5lcXVhbHMoIk1GbG9h
dCIpKQ0Kew0KICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIkFueVR5cGUiLCBuZXcgTUZsb2F0KHN0
cmluZykpOw0KfQ0KZWxzZSBpZiAodHlwZS5lcXVhbHMoIkRvdWJsZSIpKQ0Kew0KICBJRGF0YVV0
aWwucHV0KGN1cnNvciwgIkFueVR5cGUiLCBuZXcgRG91YmxlKHN0cmluZykpOw0KfQ0KZWxzZSBp
ZiAodHlwZS5lcXVhbHMoIk1Eb3VibGUiKSkNCnsNCiAgSURhdGFVdGlsLnB1dChjdXJzb3IsICJB
bnlUeXBlIiwgbmV3IE1Eb3VibGUoc3RyaW5nKSk7DQp9DQplbHNlIGlmICh0eXBlLmVxdWFscygi
Qm9vbGVhbiIpKQ0Kew0KICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIkFueVR5cGUiLCBuZXcgQm9v
bGVhbihzdHJpbmcpKTsNCn0NCmVsc2UgaWYgKHR5cGUuZXF1YWxzKCJNQm9vbGVhbiIpKQ0Kew0K
ICBJRGF0YVV0aWwucHV0KGN1cnNvciwgIkFueVR5cGUiLCBuZXcgTUJvb2xlYW4oc3RyaW5nKSk7
DQp9DQplbHNlIGlmICh0eXBlLmVxdWFscygiQmlnRGVjaW1hbCIpKQ0Kew0KICBJRGF0YVV0aWwu
cHV0KGN1cnNvciwgIkFueVR5cGUiLCBuZXcgQmlnRGVjaW1hbChzdHJpbmcpKTsNCn0NCmVsc2Ug
aWYgKHR5cGUuZXF1YWxzKCJCaWdJbnRlZ2VyIikpDQp7DQogIElEYXRhVXRpbC5wdXQoY3Vyc29y
LCAiQW55VHlwZSIsIG5ldyBCaWdJbnRlZ2VyKHN0cmluZykpOw0KfQ0KZWxzZSBpZiAodHlwZS5l
cXVhbHMoIkNoYXJhY3RlciIpKQ0Kew0KCUlEYXRhVXRpbC5wdXQoY3Vyc29yLCAiQW55VHlwZSIs
IG5ldyBDaGFyYWN0ZXIoc3RyaW5nLmNoYXJBdCgwKSkpOw0KfQ0KZWxzZSBpZiAodHlwZS5lcXVh
bHMoIkRhdGUiKSkNCnsNCglEYXRlRm9ybWF0IGRmID0gbmV3IFNpbXBsZURhdGVGb3JtYXQoZGF0
ZUZvcm1hdCk7DQoJDQoJdHJ5IHsNCgkJSURhdGFVdGlsLnB1dChjdXJzb3IsICJBbnlUeXBlIiwg
ZGYucGFyc2Uoc3RyaW5nKSk7DQoJfSBjYXRjaCAoUGFyc2VFeGNlcHRpb24gZSkgew0KCQkvLyBU
T0RPIEF1dG8tZ2VuZXJhdGVkIGNhdGNoIGJsb2NrDQoJCWUucHJpbnRTdGFja1RyYWNlKCk7DQoJ
fQ0KfQ0KZWxzZQ0Kew0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRG9udCBrbm93IGhv
dyB0byBjb252ZXJ0IHN0cmluZyB0byAnIiArIHR5cGUgKyAiJyIpOw0KfQ0KY3Vyc29yLmRlc3Ry
b3koKTsNCg==</value>
</Values>
