<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">workbookOpen</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filePath</value>
    <value>[o] object:0:required MSWorkbook</value>
    <value>[o] object:0:required MSSheet</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1
cnNvcigpOw0KCVN0cmluZwlmaWxlUGF0aCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5l
Q3Vyc29yLCAiZmlsZVBhdGgiICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNCldvcmti
b29rIHdiID0gbnVsbDsNClNoZWV0IHNoZWV0ID0gbnVsbDsNCg0KLy9BbmFseXNlLCBvYiB4bHMg
b2RlciB4bHN4IHVuZCBcdTAwRjZmZm5lbiBkZXMgZXJzdGVuIFNoZWV0cw0KdHJ5IHsNCgkvL1Zl
cnN1Y2ggYWxzIHhscyB6dSBcdTAwRjZmZm5lbg0KCXdiID0gbmV3IEhTU0ZXb3JrYm9vayhuZXcg
RmlsZUlucHV0U3RyZWFtKGZpbGVQYXRoKSk7DQoJc2hlZXQgPSB3Yi5nZXRTaGVldEF0KDApOw0K
fSBjYXRjaCAoRmlsZU5vdEZvdW5kRXhjZXB0aW9uIGUpIHsNCgllLnByaW50U3RhY2tUcmFjZSgp
Ow0KfSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgew0KCWUucHJpbnRTdGFja1RyYWNlKCk7DQp9IGNh
dGNoIChFeGNlcHRpb24gZSkgew0KCS8vVmVyc3VjaCBhbHMgeGxzeCB6dSBcdTAwRjZmZm5lbg0K
CXRyeSB7DQoJCXdiID0gbmV3IFhTU0ZXb3JrYm9vayhuZXcgRmlsZUlucHV0U3RyZWFtKGZpbGVQ
YXRoKSk7DQoJCXNoZWV0ID0gd2IuZ2V0U2hlZXRBdCgwKTsNCgl9IGNhdGNoIChGaWxlTm90Rm91
bmRFeGNlcHRpb24gZTEpIHsNCgkJZTEucHJpbnRTdGFja1RyYWNlKCk7DQoJfSBjYXRjaCAoSU9F
eGNlcHRpb24gZTEpIHsNCgkJZTEucHJpbnRTdGFja1RyYWNlKCk7DQoJfQ0KfQ0KDQovLyBwaXBl
bGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMTsNCnBpcGVsaW5lQ3Vyc29yXzEgPSBw
aXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJN
U1dvcmtib29rIiwgd2IgKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJNU1No
ZWV0Iiwgc2hlZXQgKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw0K</value>
</Values>
