<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">utilCopyFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required sourceFilename</value>
    <value>[i] field:0:optional targetFilename</value>
    <value>[i] field:0:required sourceDirectory</value>
    <value>[i] field:0:required targetDirectory</value>
    <value>[o] field:0:required message</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJc291cmNlRmlsZW5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgInNvdXJjZUZpbGVuYW1lIiApOw0KU3RyaW5nCXRhcmdldEZpbGVuYW1lID0g
SURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJ0YXJnZXRGaWxlbmFtZSIgKTsN
ClN0cmluZwlzb3VyY2VEaXJlY3RvcnkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1
cnNvciwgInNvdXJjZURpcmVjdG9yeSIgKTsNClN0cmluZwl0YXJnZXREaXJlY3RvcnkgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInRhcmdldERpcmVjdG9yeSIgKTsNCnBp
cGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCi8vIHBpcGVsaW5lDQoNCmlmKHRhcmdldEZpbGVuYW1l
ID09IG51bGwpdGFyZ2V0RmlsZW5hbWUgPSBzb3VyY2VGaWxlbmFtZTsNCmlmKHRhcmdldERpcmVj
dG9yeSA9PSBudWxsKXRhcmdldERpcmVjdG9yeSA9IHNvdXJjZURpcmVjdG9yeTsNCg0KRmlsZUNo
YW5uZWwgb3V0Q2hhbm5lbCA9IG51bGw7DQpGaWxlQ2hhbm5lbCBpbkNoYW5uZWwgPSBudWxsOyAg
DQoNCnRyeSB7DQoJaW5DaGFubmVsID0gbmV3IEZpbGVJbnB1dFN0cmVhbShuZXcgRmlsZShzb3Vy
Y2VEaXJlY3RvcnksIHNvdXJjZUZpbGVuYW1lKSkuZ2V0Q2hhbm5lbCgpOw0KfSBjYXRjaCAoRmls
ZU5vdEZvdW5kRXhjZXB0aW9uIGUxKSB7DQoJLy8gVE9ETyBBdXRvLWdlbmVyYXRlZCBjYXRjaCBi
bG9jaw0KCWUxLnByaW50U3RhY2tUcmFjZSgpOyAgDQp9DQoNCnRyeSB7DQoJb3V0Q2hhbm5lbCA9
IG5ldyBGaWxlT3V0cHV0U3RyZWFtKG5ldyBGaWxlKHRhcmdldERpcmVjdG9yeSwgdGFyZ2V0Rmls
ZW5hbWUpKS5nZXRDaGFubmVsKCk7DQp9IGNhdGNoIChGaWxlTm90Rm91bmRFeGNlcHRpb24gZTEp
IHsNCgkvLyBUT0RPIEF1dG8tZ2VuZXJhdGVkIGNhdGNoIGJsb2NrDQoJZTEucHJpbnRTdGFja1Ry
YWNlKCk7DQp9DQp0cnkgew0KCS8vIG1hZ2ljIG51bWJlciBmb3IgV2luZG93cywgNjRNYiAtIDMy
S2IpDQogICAgaW50IG1heENvdW50ID0gKDY0ICogMTAyNCAqIDEwMjQpIC0gKDMyICogMTAyNCk7
DQogICAgbG9uZyBzaXplID0gaW5DaGFubmVsLnNpemUoKTsNCiAgICBsb25nIHBvc2l0aW9uID0g
MDsNCiAgICB3aGlsZSAocG9zaXRpb24gPCBzaXplKSB7DQogICAgICAgcG9zaXRpb24gKz0gaW5D
aGFubmVsLnRyYW5zZmVyVG8ocG9zaXRpb24sIG1heENvdW50LCBvdXRDaGFubmVsKTsNCiAgICB9
DQp9IGNhdGNoIChJT0V4Y2VwdGlvbiBlKSB7DQogICAgZS5wcmludFN0YWNrVHJhY2UoKTsNCn0N
CmZpbmFsbHkgew0KICAgIGlmIChpbkNoYW5uZWwgIT0gbnVsbCkNCgkJdHJ5IHsNCgkJCWluQ2hh
bm5lbC5jbG9zZSgpOw0KCQl9IGNhdGNoIChJT0V4Y2VwdGlvbiBlKSB7DQoJCQkvLyBUT0RPIEF1
dG8tZ2VuZXJhdGVkIGNhdGNoIGJsb2NrDQoJCQllLnByaW50U3RhY2tUcmFjZSgpOw0KCQl9DQog
ICAgaWYgKG91dENoYW5uZWwgIT0gbnVsbCkNCgkJdHJ5IHsNCgkJCW91dENoYW5uZWwuY2xvc2Uo
KTsNCgkJfSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgew0KCQkJLy8gVE9ETyBBdXRvLWdlbmVyYXRl
ZCBjYXRjaCBibG9jaw0KCQkJZS5wcmludFN0YWNrVHJhY2UoKTsNCgkJfQ0KfQ0K</value>
</Values>
